<script setup>
import { hrSiteName, hrUrl } from '@/utilities/hrUrl';import {Head,Link,usePage} from '@inertiajs/vue3';import AppLayout from '@/Layouts/AppLayout.vue';import Button from '@/Components/Shadcn/Button.vue';import { ArrowLeft, Printer } from 'lucide-vue-next';defineOptions({layout:AppLayout});defineProps({report:Object,filters:Object});const page=usePage();
const LABELS={active_employees:'Employés actifs',current_contracts:'Contrats en cours',pending_leave:'Congés en attente',attendance_sessions:'Sessions de présence',attendance_minutes:'Temps constaté',approved_leave:'Congés acceptés',planning_shifts:'Créneaux planifiés'};
const label=(key)=>LABELS[key]??key.replaceAll('_',' ');
const shown=(key,value)=>key==='attendance_minutes'?`${Math.floor(value/60)} h ${value%60} min`:value;
const day=(v)=>v?new Intl.DateTimeFormat('fr-FR',{dateStyle:'long'}).format(new Date(`${v}T00:00:00`)):'—';
// Vue n'expose pas `window` au gabarit : l'impression passe par une fonction.
const printPage = () => window.print();
</script><template><Head title="Rapport RH à imprimer"/><div class="mx-auto max-w-5xl space-y-3"><div class="print-actions flex justify-between"><Button :as="Link" :href="hrUrl('/administration/reports')" size="rg" variant="white-outline"><ArrowLeft class="h-4 w-4 shrink-0" />Retour</Button><Button size="rg" @click="printPage"><Printer class="h-4 w-4 shrink-0" />Imprimer</Button></div><article class="print-doc bg-white p-8 text-slate-900"><header class="flex justify-between border-b-2 border-slate-900 pb-4"><div><strong class="uppercase">{{page.props.site?.brand||'Clinique Saint Georges'}}</strong><p class="text-xs">Site {{hrSiteName()}}</p></div><div class="text-end"><h1 class="text-xl font-black uppercase">Rapport ressources humaines</h1><p class="text-xs">Du {{day(filters.from)}} au {{day(filters.to)}}</p></div></header><div class="mt-8 grid grid-cols-2 gap-3 text-sm"><p v-for="(value,key) in report.summary" :key="key" class="border border-slate-300 p-3"><strong>{{label(key)}} :</strong> {{shown(key,value)}}</p></div><h2 class="mt-8 border-b border-slate-500 pb-1 text-sm font-black uppercase">Effectif par département</h2><table class="mt-3 w-full text-sm"><tr v-for="item in report.by_department" :key="item.uuid"><td class="border-b border-slate-200 py-2">{{item.label}}</td><td class="border-b border-slate-200 py-2 text-end font-bold">{{item.count}}</td></tr></table></article></div></template><style>@media print{.print-actions,aside,nav{display:none!important}.print-doc{padding:0!important}}</style>
