<script setup>
import { Link } from '@inertiajs/vue3';
import Button from '@/Components/UI/Button.vue';
import Icon from '@/Components/UI/Icon.vue';
import FormError from '@/Components/UI/FormError.vue';
import ValidationErrorSummary from '@/Components/UI/ValidationErrorSummary.vue';
defineProps({ form: Object, employees: [Array, Object], cancelHref: String, submitLabel: String });
defineEmits(['submit']);
const inputClass='block h-10 w-full rounded-lg border border-gray-200 bg-white px-3 text-sm text-slate-700 outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-100 dark:border-gray-800 dark:bg-gray-950 dark:text-white';
</script>
<template><form class="space-y-5" @submit.prevent="$emit('submit')"><ValidationErrorSummary :errors="form.errors" /><section class="rounded-xl border border-gray-200 bg-white shadow-sm dark:border-gray-900 dark:bg-gray-950"><header class="border-b border-gray-200 bg-gray-50/70 px-5 py-4 dark:border-gray-900 dark:bg-gray-1000/40"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-100 text-violet-700"><Icon name="clock" /></span><div><h2 class="text-sm font-bold text-slate-800 dark:text-white">Session de présence</h2><p class="text-xs text-slate-500">Saisissez les heures constatées, sans calcul automatique d’absence ou de retard.</p></div></div></header><div class="grid gap-4 p-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="mb-1.5 block text-sm font-medium">Employé *</label><select v-model="form.employee_uuid" :class="inputClass" required><option value="">Sélectionner</option><option v-for="employee in employees" :key="employee.uuid" :value="employee.uuid">{{ employee.employee_number }} · {{ employee.name }}{{ employee.department ? ` · ${employee.department}` : '' }}</option></select><FormError v-if="form.errors.employee_uuid">{{ form.errors.employee_uuid }}</FormError></div><div><label class="mb-1.5 block text-sm font-medium">Entrée *</label><input v-model="form.started_at" type="datetime-local" :class="inputClass" required><FormError v-if="form.errors.started_at">{{ form.errors.started_at }}</FormError></div><div><label class="mb-1.5 block text-sm font-medium">Sortie</label><input v-model="form.ended_at" type="datetime-local" :class="inputClass"><FormError v-if="form.errors.ended_at">{{ form.errors.ended_at }}</FormError></div><div class="sm:col-span-2"><label class="mb-1.5 block text-sm font-medium">Observation</label><textarea v-model="form.observation" rows="4" class="w-full rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm dark:border-gray-800 dark:bg-gray-950 dark:text-white" /><FormError v-if="form.errors.observation">{{ form.errors.observation }}</FormError></div></div></section><div class="flex justify-end gap-2"><Button :as="Link" :href="cancelHref" size="rg" variant="white-outline">Annuler</Button><Button size="rg" :disabled="form.processing"><Icon name="check" /><span class="ms-2">{{ form.processing ? 'Enregistrement…' : submitLabel }}</span></Button></div></form></template>
